# Basic
work_dir: ./work_dir/train_gait_v5
phase: train
device: ["cuda:1"]
action_type: gait

# Log
save_score: False

# feeder
feeder: STGCN.feeder.Feeder
train_feeder_args:
  data_path: “”“YOUR_DATA_PATH“”“
  label_path : “”“YOUR_DATA_PATH“”“
  random_choose: True
  random_move: True
  window_size: 45
  # debug: True
test_feeder_args:
  data_path: “”“YOUR_DATA_PATH“”“
  label_path : “”“YOUR_DATA_PATH“”“
  # debug: True

# model
model: STGCN.net.ST_GCN
model_args:
  num_class: 5
  channel: 3
  window_size: 45
  num_point: 32
  dropout: 0.2
  graph: STGCN.graph.Azure
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True
  # backbone_config:
  # - [16,16,1]
  # - [16,16,1]
  # - [16,16,1]
  # - [16,32,2]
  # - [32,32,1]
  # - [32,32,1]
  # - [32,64,2]
  # - [64,64,1]
  # - [64,64,1]

# training
base_lr: 0.01
nesterov: True
step: [40, 80, 120]
batch_size: 256
test_batch_size: 512
num_epoch: 150
weight_decay: 0.01